---
functional:
  - Мультиязычность задач ( русский и английский )
  - Возможность выбора сложности 
  - Возможность игры с ботом, либо с реальными людьми 
  - Возможность просмотра истории баттлов
  - Возможность авторизации через Github
  - Возможность авторизации через Discord 
  - Поддержка наиболее популярных языков программирования 
  - Возмонжость выбора языка программирования в терминале баттла
  - Возможность авторизации с указанием E-mail и пароля 
  - Возможность просмотра повтора баттла 
  - Возможность пользователя присоединиться к турниру
  - Возможность участвовать только в одном баттле одновременно
  - Возможность просмотра баттла зрителям в режиме online
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  
implicit:
  - Участник не может писать и изменять код соперника
  - Зрители не могут писать код и вносить изменения в код участников
  - Возможность сортировки истории баттлов
  - Возможность пригласить в игру по ссылке
  - Участники не могут вносить изменения в предустановленную задачу баттла
  - Чат для участников турнира
